exports.socketListener = {
  USER: "user",
  ACTIVE: "active",
  INACTIVE: "inactive",
  BOTCHAT: "botChat",
  CHAT: "chat",
  CHATREQUEST: "chatRequest",
  CHATNOTIFICATION: "chatNotification",
  RESPONSEREQUEST: "responseRequest",
  SENDMESSAGE: "sendMessage",
  SENDPROMPT: "sendPrompt",
  LEAVEROOM: "leaveRoom",
  ERROR: "error",
  NEWMESSAGE: "newMessage",
  NEWRESPONSE: "newResponse",
  PREVIOUSCHAT: "previousChat",
  PREVIOUSBOTCHAT: "previousChat",
  JOINGROUP: "joinGroup",
  SENDMESSAGEGROUP: "sendMessageGroup",
  LEAVEGROUP: "leaveGroup",
  GROUPINFO: "groupInfo",
  NEWANNOUNCEMENT: "newAnnouncement",
};
